### ISSUE TITLE
Wiki structure

### ISSUE THREAD

**Issue by nheeren** [IndEcol/OpenScience#3]
We should talk about structuring this wiki. What do you think about the following:

README.md -- *add an index here*
- meta -- *for discussions, etc.*
   - one `.md` per discussion thread
  - `wiki_structure.md`
- open data working group -- *the playground for the DTTF or whatever they will be called*
  - minutes -- *minutes from meetings, etc,*
    - meeting A
    - meeting ...
    - meeting n
- resources
  - data sources useful for IE researcher -- *basically a collection of links for now*
  - other tools, etc.

**Comment by nheeren** [comment]
Seems like I can't delete [the file](https://github.com/IndEcol/OpenScience/wiki/Wiki-structure) without pulling & pushing...

**Comment by konstantinstadler** [comment]
So based on #1 we can get rid of meta

**Comment by nheeren** [comment]
A new try

```
README.md
|-- working groups
|   |-- WG core 
|   |   |-- minutes
|   |       `-- minutes_abc.md
|   |-- WG IE ontology
|   |   |-- minutes
|   |   |   `-- minutes_abc.md
|   |   |-- some_work_document.md
|   |   `-- literature_review.md
|   |-- WG IE data inventory
...
|   |-- WG IE database
...
|   |-- WG Incentivising transparency 
...
|-- resources
|   |-- data_sources_useful_for_IE_researcher.md --  a collection of links for now
        other tools, etc.
    `-- Procedural_best_practices.md
...

```

**Comment by ricklupton** [comment]
Sometimes real-time collaborative editing of minutes is still useful -- I've seen others stick to using google docs or equivalent for minutes and just put a link to the document in the wiki to get the best of both worlds.

**Comment by la-sch** [comment]
Hi all,

First of all, thanks for all your efforts. You started a great initiative.

I think that a wiki structure is really needed. For somebody like me who is not yet a contributor, it could be more intuitive to find things and make connections between different topics. A multi-level page structure, as Niko suggested, would be very helpful. I have a few suggestions related to 1) the start page, 2) the page structure, and 3) the mailing list.

1)	Start page
Below, you can find my suggestion for a start page. Listing the topics, as currently, might not be necessary anymore, if the page structure on the right has improved. To me, it seems more important that the purpose, the vision, and how to get started with using or contributing to the wiki are clear.

Science is a collective enterprise. New research builds on previous findings. As such, it heavily relies on reporting and sharing of research. The **purpose** of this page is to advance science in industrial ecology by promoting open science. First, industrial ecology researchers can find valuable _resources (link to be added)_ with useful data sources, and guidelines of how to implement open science in their own research work. Second, a group of interested IE researchers documents their findings and ideas regarding open science for industrial ecology to provide further recommendations in the future.
**Vision**
Our vision is to enhance IE research transparency, reproducibility, and ultimately impact on human well-being and environmental sustainability.
**Join us**
This is a community effort. If you're interested in open science within IE, join us! Contributions are welcome! Specific working groups are described in our [manifesto](https://github.com/IndEcol/OpenScience/wiki/IE-Open-Science-Manifesto-(work-in-progress)). You can follow our recent activities in the [minutes](https://github.com/IndEcol/OpenScience/wiki/DTTF-meeting-minutes,-2018-). Our [discussions](https://github.com/IndEcol/OpenScience/issues) take place through GitHub issues. Feel free to also join the related [mailing list](https://groups.google.com/forum/#!forum/ie-open-science).
**Recent achievements**
In early 2018, we [published](http://onlinelibrary.wiley.com/doi/10.1111/jiec.12738/full) a proposal of guidelines and incentives for sharing data. It includes minimum requirements for data sharing when publishing a scientific article, and the _Journal of Industrial Ecology_ agreed to implement these suggestions. Furthermore, it entails a data openness badge system to reward authors who supply well-documented data. Our proposal will continue to be open for debate and revision.

2)	Page structure
Since the manifesto provides an overview of the working groups, I would put it as the first item under that topic.
I would also add the DTTF as a working group where you could put the mandate as the first sub-page.
Open science trends and infrastructure is currently more about the infrastructure, which would fit well to resources.

3)	Mailing list
Since you started using GitHub issues for your communication, doesn’t it make the mailing list redundant? Having multiple communication channels might make it messy. Maybe, the mailing list could be closed (also removing the invitation on the start page to join the mailing list), and all communication would solely take place in GitHub.

Keep up the good work!

Best regards,
Laura

**Comment by nheeren** [comment]
Welcome Laura!
I agree with 1 and 2. For 3 I am not sure if issues can be a full replacement for a discussion. In my opinion issues should result in actionable items that should be concise (i.e. one issue for each issue) and can be closed once resolved.

**Comment by la-sch** [comment]
Okay, makes sense. That way the distinct purposes for communication are clear.

**Comment by la-sch** [comment]
I edited the start page in line with what I suggested here earlier, and added a custom sidebar to improve the wiki structure.
