### ISSUE TITLE
Licensing of lecture slides

### ISSUE THREAD

**Issue by nheeren** [IndEcol/OpenScience#5]
Hello! I wanted to add licensing information to my lecture slides before sharing them with the students (and possibly online at a later point). Actually, I have several questions:

1. Can you recommend a license for this specific purpose? 
2. If I use images from books and "the internet" how does that affect my options for selecting a license?
3. I am wondering if this Wiki should contain a recommendation section where we can document the findings of this issue?

**Comment by konstantinstadler** [comment]
Hi, 
Speaking based on observation (not legal knowledge):
When I have seen licences on presentations (e.g. on open science workshops/conferences) it exclusively was CC-BY 4.0. I think it is more or less the go to licences for open access (as for example by the JIE open access papers). 
Ad 2): Just add "unless otherwise noted" or "except figures on ..."
Ad 3): We can summary the points gathered here when we close the issue in the wiki
